### ISSUE TITLE
How do I reset `circleci init`?

### ISSUE THREAD

**Issue by jacebrowning** [rockymadden/circleci-cli#36]
I ran `circleci init` with an API token that lacks the appropriate access level. How can I reset the token to initialize it a second time?

**Comment by jacebrowning** [comment]
It turns out I had to find and delete the `circleci` file.
For me, this was located in `/opt/boxen/homebrew/etc/circleci-cli/`.

I suppose my feature request is to have `circleci init` **always** prompt for a token, but if I don't enter a token, use the previous token if available.

**Comment by rockymadden** [comment]
@jacebrowning Yep, makes sense. I plan on prompting folks who use a command prior to `circleci init` that they need to `init`. Additionally, executing `init` again will overwrite the existing value with the new one. Apologies on the issue.

**Comment by jacebrowning** [comment]
Perfect. Great tool, by the way!

**Comment by rockymadden** [comment]
Reopening to track that this has been addressed and merged.

**Comment by rockymadden** [comment]
@jacebrowning All the ideas mentioned above are now in place in `v0.7.0`. Thanks again for the input!
